Complete home job
Karzhavin/js-part-0 pull request #1
Opened 2022-12-10 13:36 UTC by Karzhavin

Дописал все функции из задания, поправил функцию test(), поправил тесты, где были указания на правки. Тесты все пройдены. За рамки задания не выходил, если в целом всё правильно, тогда уже со спокойной душой буду ковырять код: линтеры и yarn для меня в новинку, нужно экспериментировать))

2022-12-12 20:36 UTC, ipetropolsky requested changes

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +    return a.toString() === b.toString();
```js
areEqual([123], ['123']) // true
```
Сможешь поправить и зафиксировать тестом? Наверно не очень хорошо использовать `areEqual` для тестирования `areEqual`, но это лучше, чем ничего ) Или можно прямо руками написать что-то типа
```js
if (areEqual(true, false)) {
    throw new Error('WTF!!1');
}
```
Раз уж мы тут тестируем всё врукопашную :)

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +const getTypesOfItems = (arr) => arr.map((elmnt) => typeof elmnt);
Имя не очень. Имена переменных стараемся вообще не сокращать, особенно так.

И ещё, если уже есть функция, возвращающая тип в точно такой же ситуации, логично использовать её. В таком простом примере, конечно, нет разницы, но всё равно лучше не дублировать код. Добавишь там какую-то особенность, а тут нет, и логика разъедется. Не принципиально.

А вот в `getRealType` уже другая задача, там бы я оставил чистый `typeof`, потому что именно это и требуется.

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +    if (arr.length > 1) {
👍

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +            if (typeof arr[0] !== typeof arr[i]) {
Тут тоже самое место для `getType`. Если мы везде дублируем его реализацию, зачем он был нужен?

А есть ли смысл каждый раз получать тип первого элемента? Это семечки, просто лучше сразу привыкать не делать ничего лишнего.

И ещё глянь методы массивов, может что-то пригодится )

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +    switch (true) {
Мне тоже одно время нравился такой `switch` наизнанку, но коллеги попросили не использовать ) Тут ok.

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +        case value === Number.POSITIVE_INFINITY:
👍

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +        for (let j = i + 1; j < realTypesArray.length; j++) {
Как-то неоптимально. Сможешь сделать за один проход?

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +                realTypesArray.splice(i, 1);
Идея понятна. Но алгоритм не совсем прозрачный, ты как бы копируешь массив и начинаешь делать в нём дыры до тех пор, пока от него ничего не останется. Причём, в каждой итерации while приходится проходить по всем элементам, хотя ты уже ходил по ним в предыдущие разы и уже знаешь все типы. И вынимание элементов из массива — довольно мутная и не бесплатная операция, ни один фронтендер на память не напишет правильно `splice`, ка кминимум пойдёт проверит на MDN :)

В общем, предлагаю тут подумать ещё, если не придумывается — приходи, обсудим подробнее. Тебе в помощь идея недеструктивной обработки, безо всяких изменений.

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +        countRealTypesArray.push(`${startValue}-${counter}`);
Можно и так, но зачем склеивать и потом расклеивать, может сразу сделать массив? И ещё, вдруг в 
`startValue` попадёт значение с дефисом, это может быть крайне трудноуловимый баг.

2022-12-12 20:36 UTC, ipetropolsky commented on index.js
> +    new Set(),
Найдёшь ещё несколько?

2022-12-13 06:42 UTC, Karzhavin commented on index.js
> +            if (typeof arr[0] !== typeof arr[i]) {
Ок, буду знать.) На самом деле, я долго размышлял, а как, собственно, правильно-то сделать. Думал, а вдруг в hh практикуют процедурный подход и каждая функция должна быть вообще независимой и всё в таком духе, поэтому здесь продублировал, а дальше уже повторно использовал функции, чтобы и так, и так было))

2022-12-13 06:49 UTC, Karzhavin commented on index.js
> +    return a.toString() === b.toString();
Мда, тут я промахнулся, конечно. Что-то не подумал даже, что тестовую функцию тоже тестировать нужно))

2022-12-13 09:22 UTC, Karzhavin commented on index.js
> +    }
```suggestion
    while (realTypesArray.length > 1) {
        const firstArrayItem = realTypesArray.shift();
        if (realTypesArray.some((arrayElement) => arrayElement === firstArrayItem)) {
            return false;
        }
    }
```
Есть такой вариант, но по сути это просто махинации с синтаксисом, с точки зрения использования ресурсов те же грабли, так что пока думаю))

2022-12-13 09:54 UTC, Karzhavin commented on index.js
> +        countRealTypesArray.push(`${startValue}-${counter}`);
Идея была в том, чтобы использовать метод sort() напрямую к одноуровневому массиву спаренных значений (ну да, тут предполагалось, что значения с дефисом исключены, хз, может есть такие типы, надо поискать). С массивом массивов у меня sort() работать не хотел, поэтому вот так

2022-12-13 11:44 UTC, ipetropolsky commented on index.js
> +    return a.toString() === b.toString();
Обычно нет, но раз есть проблемы, чего бы не потестить.

2022-12-13 11:44 UTC, ipetropolsky commented on index.js
> +        countRealTypesArray.push(`${startValue}-${counter}`);
sort принимает аргументом функцию сравнения.

2022-12-13 12:23 UTC, ipetropolsky approved these changes

2022-12-13 12:23 UTC, ipetropolsky commented on index.js
> +    return arr;
Тут что-то не то, это же исходный массив.

2022-12-13 12:23 UTC, ipetropolsky commented on index.js
> +                countRealTypesArray.push([currentType, counter]);
Ооооо, а ты хорош. В Яндексе любят такие задачки, на управление курсорами и алгоритмы. Решение классное, я правда не с первого раза понял, как оно работает и почему. Фишка в проходе НЕ по исходному массиву, а по отсортированному набору типов исходного массива. Не совсем очевидно, но интересно.

Просто для понимания, как уныло мы обычно решаем такие задачи (зато экономим мозговые ресурсы свои и ревьювера):
```js
const countRealTypes = (arr) => {
    const result = {};
    arr.forEach((item) => {
        const type = getRealType(item);
        result[type] = (result[type] || 0) + 1;
    });
    return Object.keys(result)
        .sort()
        .map((type) => [type, result[type]]);
};
```
Прикольно, что твой ещё и быстрее работает: https://jsbench.me/wrlbm6ybgc/1 🔥

2022-12-13 12:23 UTC, ipetropolsky commented on index.js
> +// Hand-to-hand combat with the mistakes
😄

2022-12-13 12:23 UTC, ipetropolsky commented on index.js
> +    Symbol('123'),
👍

2022-12-13 12:42 UTC, Karzhavin commented on index.js
> +    return JSON.stringify(a) === JSON.stringify(b);
Если только ты не безработный фотограф-дизайнер, который хочет продемонстрировать весь спектр своих знаний и умений, чтобы удивить своих корешей и получить респект))

2022-12-13 12:48 UTC, Karzhavin commented on index.js
> +    return JSON.stringify(a) === JSON.stringify(b);
Про stringify интересно, я почему-то был уверен, что всё переводится в текст, как есть(ну, не считая всякие там дополнительные экранирующие символы). Да уж, загадочная JS штука

2022-12-13 12:50 UTC, Karzhavin commented on index.js
> +        uniqueRealTypeSet.add(realTypesArray[i]);
Мощно

2022-12-13 12:55 UTC, Karzhavin commented on index.js
> +    return true;
Ну, да)). Это тот случай, когда мозг спит, а руки делают)

2022-12-13 13:08 UTC, Karzhavin commented on index.js
> +    return arr;
Здесь была ещё идея вернуть [0]. Не совсем понял для себя, какой return был бы корректным на входящий пустой массив для этой функции. Можно и текст, конечно: "Массив пуст, милорд")

2022-12-13 13:33 UTC, Karzhavin commented on index.js
> +                countRealTypesArray.push([currentType, counter]);
Блин, прикольно. Счётчик интересный - result[type] = (result[type] || 0) + 1. Я с объектами меньше работал, чем с массивами, поэтому есть определённый перекос в пристрастиях при выборе пути решения

2022-12-25 08:19 UTC, merged